export const citiesData = [
  {
    id: 0,
    city: 'Tripoli',
    imgsrc: './CitiesImages/Tripoli.jpg',
    description:
      'Tripoli is the largest city in northern Lebanon and the second-largest city in the country. Situated 85 kilometers north of the capital Beirut, it is the capital of the North Governorate and the Tripoli District. Tripoli overlooks the eastern Mediterranean Sea, and it is the northernmost seaport in Lebanon',
    lat: '34.4333',
    lng: '35.8333',
    country: 'Lebanon',
    iso2: 'LB',
    admin_name: 'Liban-Nord',
    capital: 'admin',
    population: '530000',
    population_proper: '192572',
    coordinates: [34.4333, 35.8333],
    activityNumber: 5,
    activity: [{ name: 'hiking', id: 10 }],
  },
  {
    id: 1,
    city: 'Zgharta',
    imgsrc: './CitiesImages/zgharta.jpg',
    description:
      'Zgharta, also spelled Zghorta, is a city in North Lebanon. It is the second biggest city in Northern Lebanon after Tripoli.Zgharta is about 150 metres above sea level and lies between the rivers of Jouit and Rashein.',
    lat: '34.3997',
    lng: '35.8936',
    country: 'Lebanon',
    iso2: 'LB',
    admin_name: 'Liban-Nord',
    capital: 'minor',
    population: '',
    population_proper: '',
    activityNumber: 5,
    activity: [{ name: 'hiking', id: '10' }],
  },
  {
    id: 2,
    city: 'Amioun',
    imgsrc: './CitiesImages/amioun.jpg',
    description:
      'Located in the heart of Northern Lebanon, Amioun is the administrative center of Koura District. Amioun is about 370 meters (1083 feet) above sea level and approximately 78 kilometers away (48.5 miles) north-northeast of Beirut.Situated between the sea and the mountains, on a chain of beautiful hills that stretch from east to west, Amioun has a distinctive location and a scenic view. Surrounding the hills on which Amioun is situated are olive fields in the north and vineyards, almond orchards, and olive trees in the south.',
    lat: '34.2994',
    lng: '35.8097',
    country: 'Lebanon',
    iso2: 'LB',
    admin_name: 'Liban-Nord',
    capital: 'minor',
    population: '10000',
    population_proper: '10000',
    activityNumber: 5,
    activity: [{ name: 'hiking', id: '10' }],
  },

  {
    id: 3,
    city: 'Sir el Danniye',
    imgsrc: './CitiesImages/sir.jpg',
    description:
      'Danniyeh is a region located in Miniyeh-Danniyeh District in the North Governorate of Lebanon. The region lies east of Tripoli, extends north as far as Akkar District, south to Bsharri District and Zgharta District and as far east as Baalbek and Hermel. Dinniyeh has an excellent ecological environment filled with woodlands, orchards and groves. Several villages are located in this mountainous area, the largest town being Sir Al Dinniyeh. It has the highest point in Lebanon and the Levant, at 3,088 “Qurnt As Sawda”',
    lat: '34.3853',
    lng: '36.0311',
    country: 'Lebanon',
    iso2: 'LB',
    admin_name: 'Liban-Nord',
    capital: 'minor',
    population: '',
    population_proper: '',
    activityNumber: 5,
    activity: [{ name: 'hiking', id: '10' }],
  },
  {
    id: 4,
    city: 'Halba',
    imgsrc: './CitiesImages/halba.jpg',
    description:
      'Halba is the capital of Akkar Governorate in northern Lebanon, close to the border with Syria.',
    lat: '34.5428',
    lng: '36.0797',
    country: 'Lebanon',
    iso2: 'LB',
    admin_name: 'Aakk\u00e2r',
    capital: 'admin',
    population: '',
    population_proper: '',
    activityNumber: 5,
    activity: [{ name: 'hiking', id: '10' }],
  },
  {
    id: 5,
    city: 'Batroun',
    imgsrc: './CitiesImages/batroun.jpg',
    description:
      'Batroun is a major tourist destination in North Lebanon. The town boasts historic Roman Catholic and Greek Orthodox churches. The town is also a major beach resort with a vibrant nightlife that includes pubs and nightclubs. Citrus groves surround Batroun, and the town has been famous (from the early twentieth century) for its fresh lemonade sold at the cafés and restaurants on its main street. Biking along the Batroun coastline is also a major activity namely in late summer days. In 2009, the Batroun International Festival was born. It started hosting leading local and international artists. The festival takes place usually in July and/or August of each year in the old harbor area.',
    lat: '34.2553',
    lng: '35.6581',
    country: 'Lebanon',
    iso2: 'LB',
    admin_name: 'Liban-Nord',
    capital: 'minor',
    population: '',
    population_proper: '',
    activityNumber: 5,
    activity: [{ name: 'hiking', id: '10' }],
  },
  {
    id: 6,
    city: 'Bcharre',
    imgsrc: './CitiesImages/bcharre.jpg',
    description:
      'Bsharri is the town of the only remaining and preserved original Cedars of God (Cedrus libani), and is the birthplace of the famous poet, painter and sculptor Khalil Gibran who now has a museum in the town to honour him. Moreover, Bsharri is home to the oldest skiing area, the Cedars Ski Resort, and to Lebanon’s first ski lift, built in 1953. The resort is about a two-hour drive and 130 km (81 mi) from Beirut. Qurnat as Sawdā Mountain in Bsharri is the highest peak in the Levant, at 3,088 meters above sea level',
    lat: '34.2514',
    lng: '36.0972',
    country: 'Lebanon',
    iso2: 'LB',
    admin_name: 'Liban-Nord',
    capital: 'minor',
    population: '',
    population_proper: '',
    activityNumber: 5,
    activity: [{ name: 'hiking', id: '10' }],
  },
];
